package net.kitcake.griefpest;

public enum Options {
    CAN_PLACE,
    CAN_BREAK_BLOCKS,
    CAN_PVP,
    CAN_PVE_ANIMALS,
    CAN_PVE_MONSTERS,
    CAN_PVE_NPC,
    CAN_OPEN_CHESTS,
    CAN_INTERACT,
    CREEPERS_EXPLOSIONS,
    TNT_EXPLOSIONS,
    OTHERS_EXPLOSIONS,
    CAN_BREAK_ITEM_FRAMES,
    CAN_MOUNT_ENTITIES,
    CAN_ENTER_VEHICLES,
    CAN_BREAK_VEHICLES,
    FALL_DAMAGE,
    NATURAL_ANIMALS_SPAWN,
    NATURAL_MONSTERS_SPAWN,
    CAN_INTERACT_WITH_NPC,
    CAN_LIGHTNING_STRIKE,
    CAN_BURN_BLOCKS
}
